server:
  port: 8090
spring:
  application:
      name: employee-service
  datasource:
    url: jdbc:h2:mem:hrmsdb;DB_CLOSE_DELAY=-1;MODE=HSQLDB;NON_KEYWORDS=ID;
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialize: true
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  sql:
    init:
      mode: always
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      reactor.netty.http.client: TRACE
      org.hibernate,type: trace
      org.reactor:netty: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true